name: marealtaflutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
  - 'assets/images/SaoSebastiao.jpg'
  - 'assets/images/SaoSebastiao2.jpg'
  - 'assets/images/PraiaJuquehy.jpg'
  - 'assets/images/PraiaCamburizinho.jpg'
  - 'assets/images/PraiaCalhetas.jpg'
  - 'assets/images/CachoeiraSerpente.jpg'
  - 'assets/images/AmoraHotel.jpg'
  - 'assets/images/HiuHotel.jpg'
  - 'assets/images/VillaMare.jpg'
